{
  "extends": ["eslint:recommended", "plugin:react/recommended"],
  "parser": "babel-eslint",
  "globals": { "fetch": false,
               "console": false,
               "Map": false, 
               "Promise": false, 
               "it": false,
               "require": false,
               "navigator": false
               }
}